/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThAnchor: typeof import('./src/components/th-anchor/index.vue')['default']
    ThAutocomplete: typeof import('./src/components/th-autocomplete/index.vue')['default']
    ThButton: typeof import('./src/components/th-button/index.vue')['default']
    ThLink: typeof import('./src/components/th-link/index.vue')['default']
    ThSpinner: typeof import('./src/components/th-spinner/index.vue')['default']
  }
}
